# Generated by Django 3.2.3 on 2021-05-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('Enrollment_no', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=215)),
                ('Uni_Email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=215)),
            ],
        ),
    ]
