# Generated by Django 3.1.7 on 2021-05-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('Lat', models.FloatField()),
                ('Long', models.FloatField()),
                ('button', models.FloatField()),
                ('Des', models.CharField(max_length=400)),
            ],
        ),
    ]
