# Generated by Django 3.1.7 on 2021-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='button',
            field=models.CharField(max_length=200),
        ),
    ]
